export const CORRECT_ANSWER = 'CORRECT_ANSWER';
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER';
export const DONT_KNOW_ANSWER = 'DONT_KNOW_ANSWER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const LOAD_GAME = 'LOAD_GAME';
export const OPEN_LESSON_SELECT = 'OPEN_LESSON_SELECT';